service: fastapi-aws-starter-kit
# https://www.serverless.com/framework/docs/environment-variables
useDotenv: true
package:
  individually: true
provider:
  name: aws
  runtime: python3.9
  region: ${file(./serverless-config.${opt:stage, 'dev'}.json):STAGE, "us-west-2"}
  httpApi:
    cors: true
  timeout: 10
  memorySize: 128
plugins:
  - serverless-python-requirements
  - serverless-offline
functions:
  app:
    package:
      patterns:
        - "fastapi_aws_starter_kit/**"
    handler: fastapi_aws_starter_kit.handler.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
custom:
  pythonRequirements:
    dockerizePip: true
